### PR TITLE
oSPARC viewers

### PR DESCRIPTION
**Pull request by ignapas**
# Description

Small backend work for serving the list of oSPARC viewers to the frontend.
It uses the oSPARC API to get the available viewers and stores them in memory to serve them to the frontend.
It asks for the viewers:
* Once before the first request
* Once a day after that

env variable OSPARC_API_HOST defines the target oSPARC API, https://osparc.io/v0 by default.

## Type of change

New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Added two tests testing that ``/get_osparc_data`` always contains viewers information and that ``/sim/dataset/<id>`` raises an HttpException if Discover response is not ok.
## How to test
Check out https://github.com/nih-sparc/sparc-app/pull/251 and follow instructions on the PR

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by JeremyLecoeur — APPROVED** [review]
This looks good to me. Could we get a unit test for it, though?

**Comment by ignapas** [comment]
> This looks good to me. Could we get a unit test for it, though?

When trying to run the tests, I get the following errors... Sorry, I am no Python expert, maybe you can quickly tell me what's going on.
```
========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.6.9, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/ignapas/workspace/sparc-api
collected 0 items / 4 errors                                                                                                                                                                           

================================================================================================ ERRORS ================================================================================================
__________________________________________________________________________________ ERROR collecting tests/test_api.py __________________________________________________________________________________
ImportError while importing test module '/home/ignapas/workspace/sparc-api/tests/test_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_api.py:2: in <module>
    from app import app
E   ImportError: cannot import name 'app'
_______________________________________________________________________________ ERROR collecting tests/test_biolucida.py _______________________________________________________________________________
ImportError while importing test module '/home/ignapas/workspace/sparc-api/tests/test_biolucida.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_biolucida.py:3: in <module>
    from app.main import authenticate_biolucida, thumbnail_by_image_id, image_info_by_image_id
E   ModuleNotFoundError: No module named 'app.main'
________________________________________________________________________________ ERROR collecting tests/test_health.py _________________________________________________________________________________
ImportError while importing test module '/home/ignapas/workspace/sparc-api/tests/test_health.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_health.py:7: in <module>
    from app.main import health
E   ModuleNotFoundError: No module named 'app.main'
_______________________________________________________________________________ ERROR collecting tests/test_scicrunch.py _______________________________________________________________________________
ImportError while importing test module '/home/ignapas/workspace/sparc-api/tests/test_scicrunch.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_scicrunch.py:3: in <module>
    from app import app
E   ImportError: cannot import name 'app'
=========================================================================================== warnings summary ===========================================================================================
venv/lib/python3.6/site-packages/nose/importer.py:12
  /home/ignapas/workspace/sparc-api/venv/lib/python3.6/site-packages/nose/importer.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import find_module, load_module, acquire_lock, release_lock

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================================================================================= short test summary info ========================================================================================
ERROR tests/test_api.py
ERROR tests/test_biolucida.py
ERROR tests/test_health.py
ERROR tests/test_scicrunch.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================================== 1 warning, 4 errors in 0.14s =====================================================================================
```

**Comment by alan-wu** [comment]
> 
> 
> > This looks good to me. Could we get a unit test for it, though?
> 
> When trying to run the tests with `pytest`, I get the following errors... Sorry, I am no Python expert, maybe you can quickly tell me what's going on.
> 
> ```
> ========================================================================================= test session starts ==========================================================================================
> platform linux -- Python 3.6.9, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
> rootdir: /home/ignapas/workspace/sparc-api
> collected 0 items / 4 errors                                                                                                                                                                           
> 
> ================================================================================================ ERRORS ================================================================================================
> __________________________________________________________________________________ ERROR collecting tests/test_api.py __________________________________________________________________________________
> ImportError while importing test module '/home/ignapas/workspace/sparc-api/tests/test_api.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> tests/test_api.py:2: in <module>
>     from app import app
> E   ImportError: cannot import name 'app'
> _______________________________________________________________________________ ERROR collecting tests/test_biolucida.py _______________________________________________________________________________
> ImportError while importing test module '/home/ignapas/workspace/sparc-api/tests/test_biolucida.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> tests/test_biolucida.py:3: in <module>
>     from app.main import authenticate_biolucida, thumbnail_by_image_id, image_info_by_image_id
> E   ModuleNotFoundError: No module named 'app.main'
> ________________________________________________________________________________ ERROR collecting tests/test_health.py _________________________________________________________________________________
> ImportError while importing test module '/home/ignapas/workspace/sparc-api/tests/test_health.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> tests/test_health.py:7: in <module>
>     from app.main import health
> E   ModuleNotFoundError: No module named 'app.main'
> _______________________________________________________________________________ ERROR collecting tests/test_scicrunch.py _______________________________________________________________________________
> ImportError while importing test module '/home/ignapas/workspace/sparc-api/tests/test_scicrunch.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> tests/test_scicrunch.py:3: in <module>
>     from app import app
> E   ImportError: cannot import name 'app'
> =========================================================================================== warnings summary ===========================================================================================
> venv/lib/python3.6/site-packages/nose/importer.py:12
>   /home/ignapas/workspace/sparc-api/venv/lib/python3.6/site-packages/nose/importer.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>     from imp import find_module, load_module, acquire_lock, release_lock
> 
> -- Docs: https://docs.pytest.org/en/latest/warnings.html
> ======================================================================================= short test summary info ========================================================================================
> ERROR tests/test_api.py
> ERROR tests/test_biolucida.py
> ERROR tests/test_health.py
> ERROR tests/test_scicrunch.py
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> ===================================================================================== 1 warning, 4 errors in 0.14s =====================================================================================
> ```

I have experienced similar problem, Your probably need to set the PYTHONPATH to the top directory of the repository.

**Comment by ignapas** [comment]
> This looks good to me. Could we get a unit test for it, though?

tests added

**Pull request merged**
