### PR TITLE
Scaffoldstate

### PR DESCRIPTION
**Pull request by alan-wu**
# Description

Add APIs to store scaffold state similar to the one used by Map.

## Type of change

Delete those that don't apply.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Unit tests have been added to make sure this is run correctly. This can also be tested here: 

The following link should restored the scaffold to a specific viewport
https://alan-wu-sparc-app.herokuapp.com/datasets/scaffoldviewer?scaffold=105%2F2%2Ffiles%2Fderivative%2FScaffold%2FratStomach_metadata.json&id=ea8add74
New link will also be copied when the share link button is pressed at the top right corner of the scaffold viewer.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Tehsurfer — APPROVED** [review]
Looks good to me!

**Comment by alan-wu** [comment]
@hsorby Can you review this one please?

**Review by hsorby — APPROVED** [review]

**Review by Tehsurfer — APPROVED** [review]
Looks good to me!

**Review by nickerso — APPROVED** [review]
reviewed by @hsorby and @Tehsurfer

**Pull request merged**
